export const defense: { [key: string]: { [key: string]: number } } = {
  normal: {
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    ice: 1,
    fighting: 2,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 0,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  fire: {
    normal: 1,
    fire: 1 / 2,
    water: 2,
    grass: 1 / 2,
    electric: 1,
    ice: 1 / 2,
    fighting: 1,
    poison: 1,
    ground: 2,
    flying: 1,
    psychic: 1,
    bug: 1 / 2,
    rock: 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1 / 2,
    fairy: 1 / 2,
  },
  water: {
    normal: 1,
    fire: 1 / 2,
    water: 1 / 2,
    grass: 2,
    electric: 2,
    ice: 1 / 2,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1 / 2,
    fairy: 1,
  },
  grass: {
    normal: 1,
    fire: 2,
    water: 1 / 2,
    grass: 1 / 2,
    electric: 1 / 2,
    ice: 2,
    fighting: 1,
    poison: 2,
    ground: 1 / 2,
    flying: 2,
    psychic: 1,
    bug: 2,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  electric: {
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1 / 2,
    ice: 1,
    fighting: 1,
    poison: 1,
    ground: 2,
    flying: 1 / 2,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1 / 2,
    fairy: 1,
  },
  fighting: {
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    ice: 1,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 2,
    psychic: 2,
    bug: 1 / 2,
    rock: 1 / 2,
    ghost: 0,
    dragon: 1,
    dark: 1 / 2,
    steel: 1,
    fairy: 1,
  },
  ice: {
    normal: 1,
    fire: 2,
    water: 1,
    grass: 1,
    electric: 1,
    ice: 1 / 2,
    fighting: 2,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 2,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 2,
    fairy: 1,
  },
  poison: {
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1 / 2,
    electric: 1,
    ice: 1,
    fighting: 1 / 2,
    poison: 1 / 2,
    ground: 2,
    flying: 1,
    psychic: 2,
    bug: 1 / 2,
    rock: 1 / 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1 / 2,
  },
  ground: {
    normal: 1,
    fire: 1,
    water: 2,
    grass: 2,
    electric: 0,
    ice: 2,
    fighting: 1,
    poison: 1 / 2,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1 / 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  flying: {
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1 / 2,
    electric: 2,
    ice: 2,
    fighting: 1 / 2,
    poison: 1,
    ground: 0,
    flying: 1,
    psychic: 1,
    bug: 1 / 2,
    rock: 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  psychic: {
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    ice: 1,
    fighting: 1 / 2,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1 / 2,
    bug: 2,
    rock: 1,
    ghost: 2,
    dragon: 1,
    dark: 2,
    steel: 1,
    fairy: 1,
  },
  bug: {
    normal: 1,
    fire: 2,
    water: 1,
    grass: 1 / 2,
    electric: 1,
    ice: 1,
    fighting: 1 / 2,
    poison: 1,
    ground: 1 / 2,
    flying: 2,
    psychic: 1,
    bug: 1,
    rock: 2,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 1,
    fairy: 1,
  },
  rock: {
    normal: 1 / 2,
    fire: 1 / 2,
    water: 2,
    grass: 2,
    electric: 1,
    ice: 1,
    fighting: 2,
    poison: 1 / 2,
    ground: 2,
    flying: 1 / 2,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 1,
    dark: 1,
    steel: 2,
    fairy: 1,
  },
  ghost: {
    normal: 0,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    ice: 1,
    fighting: 0,
    poison: 1 / 2,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1 / 2,
    rock: 1,
    ghost: 2,
    dragon: 1,
    dark: 2,
    steel: 1,
    fairy: 1,
  },
  dragon: {
    normal: 1,
    fire: 1 / 2,
    water: 1 / 2,
    grass: 1 / 2,
    electric: 1 / 2,
    ice: 2,
    fighting: 1,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1,
    rock: 1,
    ghost: 1,
    dragon: 2,
    dark: 1,
    steel: 1,
    fairy: 2,
  },
  dark: {
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    ice: 1,
    fighting: 2,
    poison: 1,
    ground: 1,
    flying: 1,
    psychic: 0,
    bug: 2,
    rock: 1,
    ghost: 1 / 2,
    dragon: 1,
    dark: 1 / 2,
    steel: 1,
    fairy: 2,
  },
  steel: {
    normal: 1 / 2,
    fire: 2,
    water: 1,
    grass: 1 / 2,
    electric: 1,
    ice: 1 / 2,
    fighting: 2,
    poison: 0,
    ground: 2,
    flying: 1 / 2,
    psychic: 1 / 2,
    bug: 1 / 2,
    rock: 1 / 2,
    ghost: 1,
    dragon: 1 / 2,
    dark: 1,
    steel: 1 / 2,
    fairy: 1 / 2,
  },
  fairy: {
    normal: 1,
    fire: 1,
    water: 1,
    grass: 1,
    electric: 1,
    ice: 1,
    fighting: 1 / 2,
    poison: 2,
    ground: 1,
    flying: 1,
    psychic: 1,
    bug: 1 / 2,
    rock: 1,
    ghost: 1,
    dragon: 0,
    dark: 1 / 2,
    steel: 2,
    fairy: 1,
  },
}
