version: '3.8'

services:
  app:
    build: .
    container_name: app-pokemon
    env_file:
      - .env.example
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
      - DB_HOST=127.0.0.1 # Nom du service "db" dans ce fichier
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      # - DB_NAME=yourdatabase
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - my-network

  db:
    image: mysql:8.0.39
    container_name: database-pokemon
    environment:
      DB_PASSWORD: root
      DB_DATABASE: ranniquest
      DB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
